apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: service-http
      port: 7788
      targetPort: 80
  selector:
    app: frontend-deployment
